import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import GlobalWrapper from "../components/Organisms/GlobalWrapper";
import { GlobalProvider } from "../context/GlobalContext";
import "./globals.scss";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}>
        <GlobalProvider>
          <GlobalWrapper>{children}</GlobalWrapper>
        </GlobalProvider>
      </body>
    </html>
  );
}
